spring:
  main:
    web-application-type: servlet
  application:
    name: Kedostt-Backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000

imagekit:
  publicKey: ${IMAGEKIT_PUBLICKEY}
  privateKey: ${IMAGEKIT_PRIVATEKEY}
  urlEndpoint: ${IMAGEKIT_URLENDPOINT}